### ISSUE TITLE
No sources for drivers

### ISSUE THREAD

**Issue by dClauzel** [nikshepsvn/py_noise#1]
There are no sources for the drivers. It is *very* problematic to run untrusted code.

**Comment by nikshepsvn** [comment]
That's weird. I'm using the official chrome drivers from Google. There shouldn't be a problem. You don't need to install the drivers btw, the code should be able to automatically use them. Which OS are you on? Can I see a screenshot of it asking for a valid certificate or something? Thanks

**Comment by nikshepsvn** [comment]
Hey @dClauzel, do you have any info on the situation so I can work on the issue?

**Comment by nikshepsvn** [comment]
Hey @dClauzel, I will have to close this until you can give me some more details, feel free to open it up again with more information!
